### ISSUE TITLE
SMTP requires username to be an email

### ISSUE THREAD

**Issue by manumrtf** [HiEventsDev/Hi.Events#102]
While trying to register using Postmark for the email, Postmark gives a username that is not an email, then the register endpoint throws the following error:
"501 Username used for auth is not valid email address\"
however, Postmark username is something like this: xxxxxx-xxxx-xxxx-xxxx-xxxxx
What should I use as username?

**Comment by daveearley** [comment]
It appears that the issue you're encountering is specific to Postmark.To resolve this, I recommend reaching out to Postmark support for assistance. They should be able to guide you through the proper setup process for a Laravel application.
