### ISSUE TITLE
🐛 Event page not available using Cloudflare tunnel 

### ISSUE THREAD

**Issue by JohnAugust934** [HiEventsDev/Hi.Events#105]
I'm using the page with Docker and to provide access outside the local network I'm using Cloudflare Tunnel. 
So far, the only problem I'm facing is the final page of the event, which with the public link does not allow people to see the page and book a ticket.
Forgive me if this is a configuration error, could anyone help me?

![image](https://github.com/user-attachments/assets/67432122-7786-4e0e-bf8c-e1392d545121)

**Comment by daveearley** [comment]
Hi @JohnAugust934,

Just to confirm, is the event set to `live`?

**Comment by JohnAugust934** [comment]
Hi @daveearley,

Sorry, how can I check this?

When I create the event, locally, it opens the page I set up for people to reserve tickets. Only when I open the page from my domain using Cloudflare does it display this message.

![image](https://github.com/user-attachments/assets/86233491-6a91-4def-a94b-289532832e9a)

**Comment by JohnAugust934** [comment]
I just found what I said, I hadn't paid attention to that detail when I was creating the event, sorry for the inconvenience.

![image](https://github.com/user-attachments/assets/e7bc2e97-0d25-4425-88cc-f0ea60c8802c)

I'll be marking it as closed, thanks for the help!
