### ISSUE TITLE
🐛 user invite email not sending

### ISSUE THREAD

**Issue by justynpride** [HiEventsDev/Hi.Events#121]
**Describe the bug**
New user on account does not receive invite email

**To Reproduce**
1. Go to 'account' and user and then invite user 
2. Fill in and submit the form
3. Error message appears
4. Refresh screen and new user appears, but no invite email has been sent. 
5. Click 'resend invite email' and another email error appears

**Expected behavior**
Invite email being sent to new user

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone SE2022
 - OS: [e.g. iOS8.1] iOS 17.5.1
 - Browser [e.g. stock browser, safari] Safari

**Hi.Events Version and platform**
Please state the version of Hi.Events you are using and what platform it is hosted on. Local, Docker etc.
0.4.0v2 docker hosted with Railway App

**Logs**
Add any relevant error logs

**Comment by daveearley** [comment]
Were there any errors in the docker container logs? Can you send other emails from the platform OK?

**Comment by justynpride** [comment]
I can send other emails fine. The log comes up with:

100.64.0.2 - - [07/Aug/2024:07:04:08 +0000] "GET /api/users HTTP/1.1" 200 871 "https://test.book-in.me/account/users"; "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1"

127.0.0.1 -  07/Aug/2024:07:04:08 +0000 "GET /index.php/users" 200

[2024-08-07 07:05:13] production.ERROR: Undefined variable $user (View: /app/backend/resources/views/emails/user/user-invited.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined variable $user (View: /app/backend/resources/views/emails/user/user-invited.blade.php) at /app/backend/storage/framework/views/3e5b1226cd05b24f8d7b83c3c6ff7c81.php:15)

[stacktrace]

**Comment by daveearley** [comment]
Thanks for passing on the log. This has been fixed in the latest release.

**Comment by justynpride** [comment]
Thank you. It works great.
