### ISSUE TITLE
Installation fails with timeout issue 🐛

### ISSUE THREAD

**Issue by gausoft** [HiEventsDev/Hi.Events#122]
**Describe the bug**
The `docker compose up` command fails to complete due to repeated network connection issues, resulting in an ESOCKETTIMEDOUT error when trying to fetch the @tabler/icons package.

**To Reproduce**
1. cd to `Hi.Events/docker/all-in-one` directory
2. run `docker compose up`
3. Observe the output during the fetching packages phase
4. Notice multiple network connection retry attempts.

**Screenshots**
![Screen Shot 2024-08-04 at 17 14 47](https://github.com/user-attachments/assets/189ce877-5516-4452-a812-0c9b7aa62934)

**Desktop:**
 - OS: MacOs
 - Version 12.7.5

**Additional context**
- The installation process described in the documentation does not work. Running docker compose up in the Hi.Events/docker/all-in-one directory seems to work but ends up timing out, even though I have a very good connection.
- When I retry, the result is the same.

**Comment by daveearley** [comment]
We're you able to solve this? This looks like a networking issue on your end rather than an issue with Hi.Events.

**Comment by gausoft** [comment]
No sorry. Always have the same issue. Maybe, it's come from the docker image??

**Comment by gausoft** [comment]
I've tried installation without docker, yarn install work nicely in frontend project, but in backend some tables seem to be missing.

**Comment by daveearley** [comment]
If you're database tables are missing you might need to run `php artisan migrate` within your `backend` directory.

**Comment by daveearley** [comment]
I'm closing this issue as it seems like an environment issue. I'll reopen if anyone else experiences something similar.
