### ISSUE TITLE
🐛 Stripe payment details, email and name

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/Hi.Events#123]
There isn't an email or name passed into Stripe for the payments.  This is useful to happen for bank reconciliation of payments.  Please have a setting to pass these details through to the Stripe payments.

**Comment by daveearley** [comment]
Good suggestion! I've [created a PR](https://github.com/HiEventsDev/Hi.Events/pull/124) to send customer data, and also additional metadata related to the order. It will be included in the next release.

**Comment by daveearley** [comment]
This is now [released](https://github.com/HiEventsDev/Hi.Events/releases/tag/v0.5.0-alpha.1). Thanks again for the suggestion.
