### ISSUE TITLE
🌟Organizer Dashboard default sorting

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/Hi.Events#129]
On the organizer dashboard, it might be an improvement to filter the events list by default so that ended events are not shown by default.  When the system has many events that have ended I don't think that these events should appear by default.  All the old events are shown at the top of this list by default as well.  I believe that it would be more useful for upcoming events to be listed at the top by default, ended events could be hidden on this screen.

**Comment by daveearley** [comment]
That's a good point! Finished events should be filtered. This page will be [redesigned soon](https://github.com/orgs/HiEventsDev/projects/1/views/1?pane=issue&itemId=72908769) and I'll take this into account.

**Comment by daveearley** [comment]
This feature has been added in the [latest release](https://github.com/HiEventsDev/Hi.Events/releases/tag/v0.7.0-alpha.1). Thanks again for the suggestion.
