### ISSUE TITLE
wrong variable name at backend/resources/views/vendor/mail/html/message.blade.php 🐛

### ISSUE THREAD

**Issue by hernopugliese** [HiEventsDev/Hi.Events#133]
**Describe the bug**

at backend/resources/views/vendor/mail/html/message.blade.php 

the line @if($appEmailFooter = config('app.email_footer'))
should be @if($appEmailFooter = config('app.email_footer_text'))

so it can match env('APP_EMAIL_FOOTER_TEXT') at backend/config/app.php

**Additional context**
A simple contribution
**Thank You Very Much** for your work, please include somewhere a link to U$D contribute to you.

**Comment by daveearley** [comment]
Thanks for the report @hernopugliese!

**Comment by daveearley** [comment]
Merged in https://github.com/HiEventsDev/Hi.Events/pull/158. Will be included in the next release. Thanks again for the report.
