### ISSUE TITLE
🐛 Wrong Variable name at /backend/resources/views/emails/user/user-invited.blade.php

### ISSUE THREAD

**Issue by hernopugliese** [HiEventsDev/Hi.Events#134]
at /backend/resources/views/emails/user/user-invited.blade.php

{{ __('Hi :name', ['name' => $User->getFirstName()]) }},

Should be

{{ __('Hi :name', ['name' => $invitedUser->getFirstName()]) }},

THANKS

**Comment by justynpride** [comment]
I think you might find this was fixed in the last release v0.5.0-alpha.2?

**Comment by daveearley** [comment]
Thanks for the report @hernopugliese, but as @justynpride said, this has been fixed in the last release.
