### ISSUE TITLE
🐛Ticket summary doesn't show correct currency

### ISSUE THREAD

**Issue by justynpride** [HiEventsDev/Hi.Events#147]
**Describe the bug**
Ticket summary in dashboard doesn't show correct currency unit. Minor issue, but good to correct.

**To Reproduce**
1. Created an event with tickets with a currency other than dollar
<img width="999" alt="Screenshot 2024-08-19 at 08 00 56" src="https://github.com/user-attachments/assets/2157aaeb-594a-4ed9-a8c9-3ffae336a5da">

2. Go to 'manage/event/3/tickets' 
3. View the list of tickets and check currency displayed. 
<img width="1090" alt="Screenshot 2024-08-19 at 08 00 46" src="https://github.com/user-attachments/assets/45f2fa4b-b14a-4704-9586-9ed5d9f7976a">

**Expected behavior**
As the event currency is British Pound, I would expect the currency to show next to the ticket price to be British Pound not Dollar. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 14.6.1
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 17.6

**Hi.Events Version and platform**
v0.6.0-alpha.3, Docker hosted with Railway.

**Comment by daveearley** [comment]
Thanks for the report @justynpride! I'll fix this in the next release.

**Comment by daveearley** [comment]
Fixed in [v0.7.0-alpha.1](https://github.com/HiEventsDev/Hi.Events/releases/tag/v0.7.0-alpha.1). Thanks again.
