### ISSUE TITLE
🐛Currency doesn't save on new organiser creation

### ISSUE THREAD

**Issue by justynpride** [HiEventsDev/Hi.Events#148]
Describe the bug
When creating a new user/organiser the Currency doesn't save, and so you need to then change in the user profile. Minor issue, but good to correct.

To Reproduce

1. Create a new user at '/auth/register', and select a currency other than USD. 
<img width="950" alt="Screenshot 2024-08-20 at 08 04 42" src="https://github.com/user-attachments/assets/edaeb102-e521-4ee5-8f5d-88cca312aa55">
2. Save
3. Create event, or skip and go to '/account/settings'. The currency is still defaulted to USD
<img width="960" alt="Screenshot 2024-08-20 at 08 04 59" src="https://github.com/user-attachments/assets/c222262a-a5ef-41ea-94c2-5fab1dad234d">

Expected behavior
Selected currency to be saved. 

Desktop (please complete the following information):

OS: [e.g. iOS] 14.6.1
Browser [e.g. chrome, safari] Safari
Version [e.g. 22] 17.6
Hi.Events Version and platform
v0.6.0-alpha.3, Docker hosted with Railway.

**Comment by daveearley** [comment]
Fixed in [v0.7.0-alpha.1](https://github.com/HiEventsDev/Hi.Events/releases/tag/v0.7.0-alpha.1). Thanks again.
