### ISSUE TITLE
🌟Duplicate event - add option / setting to duplicate the cover image

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/Hi.Events#149]
When duplicating an event, add an option / setting that will also duplicate the cover photo?  This could be disabled by default as the duplication feature doesn't currently copy over the cover photo.  We are running a recurring event where the cover photo doesn't change between the events so this would be a useful addition.

**Comment by daveearley** [comment]
Good suggestion. I'll add it to the roadmap.

**Comment by daveearley** [comment]
This has been included in the latest [v0.7.0-alpha.2](https://github.com/HiEventsDev/Hi.Events/releases/tag/v0.7.0-alpha.2) release. Thanks again for the suggestion.
