### ISSUE TITLE
[SEC] QR Code not secure

### ISSUE THREAD

**Issue by td00** [HiEventsDev/hi.events#18]
**Describe the bug**
The QR Code only contains the main Order Number and an increasing number (i.e. FOOBA-1).
This can be enumarated fairly easily and should be considered insecure

**To Reproduce**
1. Book a ticket
2. Get the QR Code
3. Scan the QR Code

**Expected behavior**
Use some unique secure random string

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Hi.Events Version and platform**
demo instance

**Logs**
Add any relevant error logs 

**Additional context**

**Comment by daveearley** [comment]
Thanks for the report @td00!  Good suggestion. Any queries involving the Attendee ID will always include the event ID, and there's a rate limit in place, so it makes enumeration a little tricky. But it's not impossible, so I'll update the public ID to use a longer more secure string. Cheers!
