### ISSUE TITLE
🌟Provide GPG Key in SECURITY.MD

### ISSUE THREAD

**Issue by td00** [HiEventsDev/hi.events#19]
**Is your feature request related to a problem? Please describe.**
There is no GPG Key for your security@ email address.

**Describe the solution you'd like**
Provide a GPG Key for your security@ email address. (preferably via a signed commit)

**Describe alternatives you've considered**
Public Disclosure

**Additional context**
If I can't make sure it only reaches the intended persons, why bother with a responsible disclosure?

**Comment by daveearley** [comment]
Good suggestion! I've added the public key to [SECURITY.md](https://github.com/HiEventsDev/hi.events/blob/develop/SECURITY.md). Thanks.
