### ISSUE TITLE
🐛Some URLs still pointing to localhost after setting app URLs

### ISSUE THREAD

**Issue by richard-lee-863** [HiEventsDev/Hi.Events#190]
**Describe the bug**
After setting the following environment variables, there are still some URLs utilizing "localhost" such as:
/checkout
/ticket

```
     - VITE_FRONTEND_URL=http://10.1.5.100:8123
     - VITE_API_URL_CLIENT=http://10.1.5.100:8123/api
     - VITE_API_URL_SERVER=http://10.1.5.100:80/api
     - APP_CDN_URL=http://10.1.5.100:8123/storage
```

**To Reproduce**
1. Order a ticket
2. Click on View ticket in email received
3. OR click on "View order summary and tickets" in email received
4. See URL not pointing to correct app URL

**Expected behavior**
I expect the URL to start with the IP address / hostname of the provided app URL

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker on Unraid
 - Browser: Firefox
 - Version: 129.0.2

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Google Pixel
 - Browser: Brave
 - Version: ??

**Hi.Events Version and platform**
Docker installation. version: v0.7.0-beta.2

**Comment by daveearley** [comment]
What value do you have for `APP_FRONTEND_URL`? Any URL that is generated on the backend uses this env variable.

**Comment by richard-lee-863** [comment]
Sorry I must have missed that one, wasn't in the compose file. I've added that now and all seems well :)

**Comment by daveearley** [comment]
Hi @rolinger1 👋 

How did you install Hi.Events?

If you're installing locally without Docker, The `VITE_*` environment variables need to be part of the environment when you run `yarn build`.

You can see an example of that [here](https://github.com/HiEventsDev/Hi.Events/blob/develop/INSTALL_WITHOUT_DOCKER.md#4-set-environment-variables).

**Comment by daveearley** [comment]
You'll to update the `VITE_*` environment variables in `./docker/all-in-one/docker-compose.yml` file. They're hardcoded to use localhost, so updating them in the `.env` will have no affect.
