### ISSUE TITLE
🐛 Nearly all checkouts fail due to session verification issue

### ISSUE THREAD

**Issue by domtie** [HiEventsDev/Hi.Events#194]
**Describe the bug**
Hi, Awesome tool! 

I'm facing an issue throughout multiple instances of the application.
More than 90% of attempts to checkout fail, nearly 100% on mobile even. 
Only error I'm able to find is: "message": "Sorry, we could not verify your session. Please restart your order."
As well as a 403 for a request to .../api/public/events/2/order/o_kWqIOlqjVXXXX?session_identifier=16265XXX.
Every now and then an attempt will go through on desktop, but rarely.

Edit: Visiting and loading the requested url directly fails/resolves randomly. Reloading 10 times will return ~7: 
"SORRY, WE COULD NOT VERIFY YOUR SESSION. PLEASE RESTART YOUR ORDER." and ~3 return the requested data. 
Same route, loaded a couple seconds apart in the browser without cache. 

**To Reproduce**
1. Go to an event page
2. Select ticket quantity
3. Click "Continue"

**Screenshots**
<img width="666" alt="Screenshot 2024-09-05 at 08 27 27" src="https://github.com/user-attachments/assets/c6bd6989-f982-455b-86f2-cb615edfdd28">

Error occurs on all end-user devices, and with near 100% frequency when on mobile.

**Hi.Events Version and platform**
I'm running the latest version (c2873ec01ddb) of the all-in-one docker image, deployed on a hetzner server.

**Additional context**
API seems to be running great, just facing issues during the checkout flow. 

Any idea if this is a deployment/config error or an issue with the container?
I'm unable to pinpoint where/if more detailed logs are stored anywhere, any advice?

Thanks :)

**Comment by domtie** [comment]
Figured out this is most likely an issue when using Cloudflare due to their load balancers rotating IPs, which will obviously fail the IP checks during checkout.

**Comment by daveearley** [comment]
Thanks for the report! This should be once https://github.com/HiEventsDev/Hi.Events/pull/195 is merged.

**Comment by daveearley** [comment]
Closing as this was solved in #197.
