### ISSUE TITLE
🌟 Provide A Way For Local Installs Without Docker

### ISSUE THREAD

**Issue by fmunim** [HiEventsDev/Hi.Events#21]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A way to install it locally without docker

**Describe alternatives you've considered**
N/A

**Additional context**
I would love to install it locally without docker. A guide? would be helpful

**Comment by daveearley** [comment]
Good idea @fmunim! It should be fairly straightforward as it's just a Laravel app with a React/Node frontend. I'll put together a guide soon.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by fmunim** [comment]
> Good idea @fmunim! It should be fairly straightforward as it's just a Laravel app with a React/Node frontend. I'll put together a guide soon.

Thank you for the quick reply! I look forward to the guide 😃!

**Comment by streamjamz** [comment]
any progress on the guide?

**Comment by daveearley** [comment]
@streamjamz Not yet sorry. I hope to have it done soon.

**Comment by tasnim0tantawi** [comment]
Will try to work on this issue

**Comment by tasnim0tantawi** [comment]
@daveearley @fmunim I have worked on a markdown file that explains how to run it locally for development (without Nginx setup). Are you okay with that? Or you want me to add Nginx guide?

**Comment by daveearley** [comment]
@tasnim0tantawi Locally I'm fine not using Nginx. For local dev, the less services, the better. Thanks for creating a guide! Looking forward to seeing it.

**Comment by daveearley** [comment]
This has now been [merged](https://github.com/HiEventsDev/Hi.Events/blob/develop/INSTALL_WITHOUT_DOCKER.md). Thanks to @tasnim0tantawi for writing the guide.
