### ISSUE TITLE
🐛QR scan wont work after attempt to checkin an invalid QR

### ISSUE THREAD

**Issue by hernopugliese** [HiEventsDev/Hi.Events#217]
**Describe the bug**
If you scan an invalid QR meaning a "Hi Event QR" that is not an valid attendee(from an another instance by examplo) the check in says invalid attendee detected, that is correct. But if you next try to scan a Valid QR or anything alse after, the check in QR Scan will not detect it with no message. If you close the scan tool and re open it will work again.

**To Reproduce**
1. Go to scan QR
2. scan invalid QR
3. scan valid QR
4. nothing happends

**Expected behavior**
after scanning a invalid QR the "scan QR" tool should check in QR from valids attendees.

**Desktop (please complete the following information):**
 - OS: ANDROID
 - Browser Chrome
 - Version LATEST at this time

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Latest

**Hi.Events Version and platform**
v0.7.0-beta.2 Docker all-in-one

**Comment by daveearley** [comment]
Thanks for the report @hernopugliese! I've found the cause and will have [a fix](https://github.com/HiEventsDev/Hi.Events/pull/223/files) released very soon.
