### ISSUE TITLE
🐛 Cancelling an Attendee doesn't cancel associated order(s)

### ISSUE THREAD

**Issue by grablair** [HiEventsDev/Hi.Events#218]
**Describe the bug**
If I cancel an attendee, the associated order is still Open. This enables me to also erroneously cancel the associated order as well. One result in this situation is that the capacity assignment will lower by double the amount (could even go into the negatives), creating a situation where you can sell more tickets than you have space for.

I'm unsure if this affects refunds... would this refund double the money? that would be very bad haha

**To Reproduce**
1. Create a ticket
2. Create a 1-person capacity assignment for that ticket
3. Create an attendee manually, for the ticket created in step 1
4. Note that the capacity assignment is now full (1/1)
5. Cancel the attendee
6. Note that the capacity assignment is now 0/1
7. Go to the orders page
8. Note that the order associated with the attendee is still open
9. Cancel the order
10. Note that the capacity assignment is now -1/1

**Expected behavior**
I shouldn't be able to do double cancellations. I'm unsure what is _right_, however. What is the purpose of cancelling an attendee? Does that refund a portion of the order? Refunding one ticket in an order seems like it would be useful.

**Screenshots**
![Screenshot 2024-09-13 at 14 35 16](https://github.com/user-attachments/assets/e2c673bc-d609-4b9c-99cb-23a9802cb3cf)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 
**Hi.Events Version and platform**
[v0.7.0-beta.3](https://github.com/HiEventsDev/Hi.Events/releases/tag/v0.7.0-beta.3) / Docker

**Comment by daveearley** [comment]
Thanks for the report @grablair! A [fix](https://github.com/HiEventsDev/Hi.Events/pull/224) will be merged soon.

> What is the purpose of canceling an attendee?

The purpose is to allow an organizer to void a single ticket. It doesn’t trigger a refund; the organizer would need to handle that separately. Ideally, all actions like refunding, canceling, etc., would be managed in the same area. I'll add this UX improvement to the roadmap.

**Comment by cgonIT** [comment]
Is normal this behaviour?

1. A client select an offline-payment ticket.
2. Me as admin, reject his reservation.
3. This reservation with "Canceled" status appears in the "Orders" page.
--> But in the "Dashboard" still appears 1 product sold, 1 attendees, "x€ Gross Sales" and "1 Complete Order"

![Image](https://github.com/user-attachments/assets/4c18ff54-5023-49ea-bc71-96c022431e7a)

![Image](https://github.com/user-attachments/assets/fdb44fde-e234-47bf-b88d-784be8ece254)

![Image](https://github.com/user-attachments/assets/eefbca6a-80b0-48ef-bfcd-bc1b81eebcfb)

I think this shouldn't be  the expected behaviour, Am I wrong?

Why is not possible to roll-back the status from "Canceled" to "Paid" for example? Why is not possible to mark the "refund" when canceling a book?

**Comment by cgonIT** [comment]
> Is normal this behaviour?
> 
> 1. A client select an offline-payment ticket.
> 2. Me as admin, reject his reservation.
> 3. This reservation with "Canceled" status appears in the "Orders" page.
>    --> But in the "Dashboard" still appears 1 product sold, 1 attendees, "x€ Gross Sales" and "1 Complete Order"
> 
> ![Image](https://github.com/user-attachments/assets/4c18ff54-5023-49ea-bc71-96c022431e7a)
> 
> ![Image](https://github.com/user-attachments/assets/fdb44fde-e234-47bf-b88d-784be8ece254)
> 
> ![Image](https://github.com/user-attachments/assets/eefbca6a-80b0-48ef-bfcd-bc1b81eebcfb)
> 
> I think this shouldn't be the expected behaviour, Am I wrong?
> 
> Why is not possible to roll-back the status from "Canceled" to "Paid" for example? Why is not possible to mark the "refund" when canceling a book?

Hi @daveearley I see (now sorry) this ticket was closed, but could you take a look to my previous message with one behaviour that (for me) was unexpected? Thank you!
