### ISSUE TITLE
🐛For Check in lists, total tickets to check in gets added incorrectly

### ISSUE THREAD

**Issue by kuhnfelix18052005** [HiEventsDev/Hi.Events#221]
**Describe the bug**
So we have a tiered Ticket, containing 3 tiers, when someone buys one of the Tiers. The total number of tickets to check in gets bumped up by 3 tickets and not by 1

![image](https://github.com/user-attachments/assets/9618fb20-07af-4192-bf13-abd2bc138623)

As you can see in the screenshot above, only 2 people have bought 1 ticket each, however the amount of tickets to scan is 6, not 2. That is wrong. 

**Expected behavior**
Have the amount be the exact number of Tiers sold per Tiered ticket

**Hi.Events Version and platform**
Latest version at moment of publication

OHH also another bug I just found... when cancelling orders with the attendees previously checked in (niche case)... The counter of tickets to check in/the ones that have been checked in doesn't reset. Basically it still shows the same number as in the screenshot even though the orders were cancelled.

**Comment by daveearley** [comment]
Thanks for the report @kuhnfelix18052005! This should be fixed in the next release.
