### ISSUE TITLE
split out aio into multiple projects

### ISSUE THREAD

**Issue by wolfspyre** [HiEventsDev/hi.events#23]
it feels like a horde of software this complex aught live in multiple distinct repos, such that things could be developed, merged, reviewed, built, deployed, independently... 

this is super cool, and I don't in any way mean to crap on yer baby. :)

**Comment by daveearley** [comment]
Hi @wolfspyre 👋,

Although the frontend and backend are independent applications, I have kept them in the same repository. This setup simplifies project execution and deployment.

The app itself is pretty simple, just an API and React frontend. If things get more complex I'll definitely look into splitting it out.

Cheers
