### ISSUE TITLE
🐛 Payment page preloads with a "Your Order c

### ISSUE THREAD

**Issue by grablair** [HiEventsDev/Hi.Events#247]
**Describe the bug**
When checking out, after submitting contact information, the payment page consistently loads with content that states "This order page is no longer available", then disappears after a few seconds and shows the Stripe payment form. 

**To Reproduce**
1. Go to an event page
2. Select a ticket to purchase
3. Enter contact info
4. Click "Continue to Payment"

**Expected behavior**
I would expect the page to indicate that it is loading (like in the right hand side of the webpage below) rather than the current behavior, which could mislead the user and cause them to close out of the checkout page if they don't happen to wait.

**Screenshots**
<img width="1800" alt="Screenshot 2024-10-02 at 00 21 35" src="https://github.com/user-attachments/assets/3de695bc-b01a-465f-9c5a-b19a87f9d821">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Various

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: iOS 18.1
 - Browser: Safari

**Hi.Events Version and platform**
DigitalOcean, Hi.Events Beta 6

**Comment by daveearley** [comment]
Thanks for the report @grablair! I'll add a fix to the next release.
