### ISSUE TITLE
🐛 Invalid timezone error when trying to register 

### ISSUE THREAD

**Issue by navin-hariharan** [HiEventsDev/Hi.Events#248]
![image](https://github.com/user-attachments/assets/962d155a-d7fc-48b0-9191-82ae4b049858)

**Comment by navin-hariharan** [comment]
I am getting this error on sign-up

**Comment by daveearley** [comment]
Hi @navin-hariharan 

Can you please open the browser dev tools post the payload that is sent to the registration endpoint.

Also, any more detail you can provide, such as platform, browser etc.

**Comment by et-hoangdv** [comment]
in my case payload timezone is  "Asia/Saigon" which is incorrect. Must be "Asia/Ho_Chi_Minh"

**Comment by daveearley** [comment]
Thanks for the additional information, @et-hoangdv. I'll look into this.

**Comment by daveearley** [comment]
@et-hoangdv This should be fixed now.
