### ISSUE TITLE
🌟Installation instructions without Docker

### ISSUE THREAD

**Issue by natrius** [HiEventsDev/Hi.Events#25]
**Is your feature request related to a problem? Please describe.**
Please add installation instructions without docker as well. Not everybody likes to use docker (although i understand if you decide docker is your way to go for convenience :) )

**Comment by streamjamz** [comment]
i would love this as well

**Comment by daveearley** [comment]
This has now been [merged](https://github.com/HiEventsDev/Hi.Events/blob/develop/INSTALL_WITHOUT_DOCKER.md). Thanks to @tasnim0tantawi for writing the guide.
