### ISSUE TITLE
🌟 Feature request: offer the possibility to offer add-ons

### ISSUE THREAD

**Issue by Gijsen** [HiEventsDev/Hi.Events#256]
Is there any way of offering a add-on?
In the current way this would be a ticket and require all information like a name and email.

This system would be perfect for us if we could also use this to sell some add-ons without requesting duplicate data

**Comment by daveearley** [comment]
Hi @Gijsen,

This is currently [in progress](https://github.com/orgs/HiEventsDev/projects/1/views/1?pane=issue&itemId=74563345). It has been requested a [few times](https://github.com/HiEventsDev/Hi.Events/issues/234) so I'm closing this as a duplicate.
