### ISSUE TITLE
🌟Translations (With weblate?)

### ISSUE THREAD

**Issue by natrius** [HiEventsDev/Hi.Events#26]
**Is your feature request related to a problem? Please describe.**
Additional languages would be really great so everybody can look at it in their native language. 

**Describe the solution you'd like**
Add weblate and something like "if translation with weblate is above 90% make it available in the language-menu, not-translated strings deefaults to english" kinda.

**Comment by natrius** [comment]
You may look into how mumble https://github.com/mumble-voip/mumble has them integrated with https://hosted.weblate.org/projects/mumble/ . That way you will get plenty of help pretty fast for that task. I know other projects as well but i can't find examples right now :D

**Comment by daveearley** [comment]
German, French, Spanish, Chinese and Portuguese translations have been added. Please open a new issue if you'd like any additional language added, and if there's enough demand I'll add it.

Thanks!
