### ISSUE TITLE
🐛When I host Hi.Events at a particular domain, it still hardcodes localhost:8123 for the domain name at cover photo

### ISSUE THREAD

**Issue by huibrian** [HiEventsDev/Hi.Events#276]
🐛When I host Hi.Events at a particular domain e.g. www.aaaaa.com then , when I upload a cover photo at /manage/event/.../homepage-designer , the path of the cover photo is http://localhost:8123/storage/event_cover/xxxxxxxxxxx.jpg instead of https://www.aaaaa.com/storage/event_cover/xxxxxxxxxxx.jpg , so the cover photo couldn't show up

**To Reproduce**
1. Be an admin of the organizer and event, go to Settings --> Tools --> Homepage Designer
2. At Home Design section, click "Change Cover" to upload the cover image
3. Then it can upload the photo at the server, but the photo shown at the page is http://localhost:8123/storage/event_cover/xxxxxxxxxxx.jpg but I have hosted it at another server with its hostname www.aaaaa.com

Please help fix it. Thanks!

**Comment by daveearley** [comment]
You likely haven't set the APP_CDN_URL environment variables. 

This is needed if hosting on your own domain.
