### ISSUE TITLE
🐛Docket Compose not working.

### ISSUE THREAD

**Issue by Pablitus** [HiEventsDev/Hi.Events#283]
> [!NOTE]
> Please stick to the template and provide as much detail as possible to help us diagnose and fix the issue.
> Low effort bug reports will be closed.

**Describe the bug**
Docket compose -d not finishing setup 
**Expected behavior**
Full install Hi Envents

**Screenshots**
<img width="515" alt="2024-11-04 11_18_17-172 16 16 172 - PuTTY" src="https://github.com/user-attachments/assets/51961fea-0885-4380-a6e2-d90330e27674">

**Hi.Events Version and platform**
Latest git repository. 
OS Alpine Linux 3.20 with Docker and Docker Compose

**Comment by daveearley** [comment]
Did you get this working? It looks like a temporary error related to one of the dependencies. It's not related to Hi.Events itself.

**Comment by Pablitus** [comment]
No

Status: Downloaded newer image for node:alpine
 ---> bd8023897f38
Step 2/20 : WORKDIR /app/frontend
 ---> Running in 3c08d11f1e59
Removing intermediate container 3c08d11f1e59
 ---> 0361114a767f
Step 3/20 : RUN apk add --no-cache yarn
 ---> Running in 4056a8077817
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
**WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied**

**Comment by Pablitus** [comment]
root@ntshievents:~/hi.events/docker/all-in-one# docker-compose up -d
Building all-in-one
Sending build context to Docker daemon   12.3MB
Step 1/20 : FROM node:alpine AS node-frontend
 ---> bd8023897f38
Step 2/20 : WORKDIR /app/frontend
 ---> Using cache
 ---> 0361114a767f
Step 3/20 : RUN apk add --no-cache yarn
 ---> Running in 4b40a89361ab
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
ERROR: unable to select packages:
  yarn (no such package):
    required by: world[yarn]
The command '/bin/sh -c apk add --no-cache yarn' returned a non-zero code: 1
ERROR: Service 'all-in-one' failed to build : Build failed

**Comment by daveearley** [comment]
Can you access this URL: [dl-cdn.alpinelinux.org/alpine/v3.20/community](https://dl-cdn.alpinelinux.org/alpine/v3.20/community) in your browser?

**Comment by Pablitus** [comment]
In my PC, yes...

In the server
root@ntshievents:~# curl dl-cdn.alpinelinux.org/alpine/v3.20/community
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.27.1</center>
</body>
</html>
root@ntshievents:~#

**Comment by daveearley** [comment]
Hi @Pablitus,

I'm going to close this as it appears to be an issue with you network, and not with Hi.Events.

I'll reopen if someone else encounters the issue.

**Comment by laurens-moonens** [comment]
I'm running into the exact same issue. Even on my PC `curl dl-cdn.alpinelinux.org/alpine/v3.22/community` results in Error 301 Moved Permanently and the Dockerfile fails on `RUN apk add --no-cache yarn`

**Comment by laurens-moonens** [comment]
Follow up: I was able to resolve it by disabling Ipv6 🤷‍♂️
