### ISSUE TITLE
🐛Custom Domain in Mailnotifications

### ISSUE THREAD

**Issue by Kohlda** [HiEventsDev/Hi.Events#291]
Iam hosting Hi.Events on a docker environment with the all in one image. In every .yml and .env i changed everything to my Domain.
In my testenvironment every customer or mail to an admin is linked with http://localhost:8123/.....

**Comment by daveearley** [comment]
Hi @Kohlda,

Can you please expand on what you mean by "mail to an admin is linked with http://localhost:8123/". 

Thanks

**Comment by trashken** [comment]
I know what OP means. The links in the email that gets sent to is set to localhost if you didn't set the APP_FRONTEND_URL.
The solution is to make sure the APP_FRONTEND_URL is present in the .env file. 
You also need to add it to the docker-compose.yml as an environment variable.
     - APP_FRONTEND_URL=${APP_FRONTEND_URL}
