### ISSUE TITLE
🌟Host the container on a public registry?

### ISSUE THREAD

**Issue by anthonyrom** [HiEventsDev/Hi.Events#299]
It would be a great convenience for many people if, instead of requiring the repository to be cloned, there were containers available on a registry (such as ghcr.io). My particular use case is wanting to install HiEvents on an UNRAID server, but in general I think that many people using Docker orchestration platforms (proxmox, etc) would find this to be a great addition. Is there a particular reason to avoid distributing this way? It seems like it would be pretty easy to add, and even automate- I'd be happy to help contribute if this would be welcomed!

**Comment by daveearley** [comment]
Hi @anthonyrom

 There are images available for every version. It's mentioned [in the docs](https://hi.events/docs/getting-started/deploying#docker-images).
