### ISSUE TITLE
🐛Can't get the local deployment running on Debian

### ISSUE THREAD

**Issue by Gijsen** [HiEventsDev/Hi.Events#305]
Hi all,

When I am trying to launch the local deployment I get the following error:

debian@vps:~/Hi.Events/docker/development$ ./start-dev.sh 
Installing Hi.Events...
Generating unsigned SSL certificates...
Generating a RSA private key
...........................................+++++
...............................................................................................................+++++
writing new private key to './certs/localhost.key'
-----
Creating network "development_app" with driver "bridge"
Creating volume "development_app-redis" with local driver
Creating volume "development_app-pgsql" with local driver
Creating volume "development_app-minio" with local driver
Building frontend
[+] Building 86.8s (7/9)                                                                                                                                                         docker:default
[+] Building 87.3s (7/9)                                                                                                                                                         docker:default
[+] Building 88.5s (7/9)                                                                                                                                                         docker:default
[+] Building 89.6s (7/9)                                                                                                                                                         docker:default
 => [internal] load build definition from Dockerfile.ssr.dev                                                                                                                               0.0s
 => => transferring dockerfile: 181B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/node:alpine                                                                                                                             0.8s
 => [internal] load .dockerignore                                                                                                                                                          0.0s
 => => transferring context: 411B                                                                                                                                                          0.0s
 => CACHED [1/5] FROM docker.io/library/node:alpine@sha256:d03e75e7ba1385c2944f4cc374eb5abe0715234f87da5121dbd64f7262ad10df                                                                0.0s
 => [internal] load build context                                                                                                                                                          0.8s
 => => transferring context: 3.50MB                                                                                                                                                        0.8s
 => [2/5] WORKDIR /app                                                                                                                                                                     0.4s
 => [3/5] COPY ./package.json ./yarn.lock ./                                                                                                                                               0.1s
 => [4/5] RUN yarn install                                                                                                                                                                87.8s
 => => # yarn install v1.22.22                                                                                                                                                                 
 => => # [1/4] Resolving packages...                                                                                                                                                           
 => => # [2/4] Fetching packages...                                                                                                                                                            
 => => # info There appears to be trouble with your network connection. Retrying...                                                                                                            
 => => # info There appears to be trouble with your network connection. Retrying...                                                                                                            
ERROR: failed to solve: Canceled: context canceled$ 

The same issue, where Fetching packages is not working also happens on the all in one docker. 

Is there any recommended setup on deploying both frontend and backend seperate and how to link both of them? Should you do this in one docker compose file? I would like to get this setup somewhere next week, if there would be anybody willing to help me would be appreciated

**Comment by iliayg** [comment]
Hi!
How did you finally figured it out?
