### ISSUE TITLE
🐛Attendees check-in status not checked in

### ISSUE THREAD

**Issue by AnonJervis** [HiEventsDev/Hi.Events#329]
**Describe the bug**
I created an event to test. Tested selling 14 tickets, 1 attendees per ticket. I then created a Check-In List for the 14 tickets and used a mobile phone to scan half of the 14 tickets for check-in, but when looking at attendees detail the "Checked In" status is still showing "no". I exported the attendees list and they also confirmed attendees are not checked in. 

**To Reproduce**
1. Created an event and tested selling 14 tickets
2. Go to "Check-In Lists" to create the list.
3. Opened Check-in page on mobile phone, use said QR code scanner to scan test tickets. 
4. Go to "Attendees", click into one of the checked in attendee for detail, Checked In status still shows "no"
5. Exported Attendees list via "Export" button, opened xlsx file to view data, under column "Is Checked In" all attendees status are showing "no"

**Expected behavior**
After scanning QR code of attendee tickets, the attendee Checked In status should show "Yes"

**Desktop (please complete the following information):**
 - OS: POP!_os
 - Chrome
 - Version 131.0.6778.204 (Official Build) (64-bit)

**Hi.Events Version and platform**
-Docker all-in-one (v0.8.0-beta.8)

**Additional context**
Just giving feedback to see if the attendees page can also show a column whether attendee has checked in or not for quicker view rather than going into detail one by one. Otherwise, loving this so far!

**Comment by daveearley** [comment]
Thanks for the report @AnonJervis! This should be fixed now. The check-in status was displaying the status from a deprecated column in the DB.

**Comment by AnonJervis** [comment]
Awesome! Thank you for the quick response!
