### ISSUE TITLE
🌟The ability to remove/delete Events

### ISSUE THREAD

**Issue by Brantlab** [HiEventsDev/Hi.Events#34]
Unable to currently delete events

I have made the event back to a draft to make it no longer public.

**Comment by daveearley** [comment]
That will be coming very soon. As well as the ability to clone events.

**Comment by kuhnfelix18052005** [comment]
Is there any progress on this part? Or a workaround?

**Comment by daveearley** [comment]
The latest release has the ability to archive events, which will hide them from the public.
