### ISSUE TITLE
🌟Ability to add ical or outlook calendar to email to be added to calendar

### ISSUE THREAD

**Issue by Brantlab** [HiEventsDev/hi.events#35]
Pretty much what the title says. An email attachment for them to block their calendar off.

**Comment by daveearley** [comment]
Thanks @Brantlab. Good suggestion!

**Comment by Brantlab** [comment]
I could probably offer a bounty on this if that helps. We are using it for non profit IT meet up scheduling. Utilizing it more as an event sign up system and event organization tool. ESP since it's all volunteer and non profit.

**Comment by daveearley** [comment]
<img width="1222" alt="Screenshot 2024-06-16 at 07 18 56" src="https://github.com/HiEventsDev/hi.events/assets/166798/ed03a80b-e987-40eb-b4c8-a63b96d59b27">

This feature has been added. Thanks again for the suggestion.
