### ISSUE TITLE
Error message when creating account

### ISSUE THREAD

**Issue by zarevskaya** [HiEventsDev/hi.events#4]
Hi,
When I create the account, it gives me this error message but the account is created.

![Screenshot_20240530_123822](https://github.com/HiEventsDev/hi.events/assets/60230221/a5d29fd3-ee67-43f7-90e6-b95008687ea0)

The account is successfully created because when I try to restart the creation I get this message:

![Screenshot_20240530_124116](https://github.com/HiEventsDev/hi.events/assets/60230221/1322be2d-c5c2-481a-95df-2727d4c2f37f)

I tested on 3 different VPS and I got the same thing.

**Comment by daveearley** [comment]
Hi @zarevskaya,

Thanks for being the first person to create an issue!

Did you see any errors in the logs when the first failure occurred? 

If you change your `APP_DEBUG` environment variable to `true` and then attempt to create an account with a different email you should see the error.

Also, please make sure you have set the `APP_KEY` and `JWT_SECRET` correctly in your environment. You can see instructions for that here: https://github.com/HiEventsDev/hi.events-digitalocean

Thanks

**Comment by zarevskaya** [comment]
Thanks for the answer! 

**Did you see any errors in the logs when the first failure occurred?** => Nope. Only on the browser.

**Also, please make sure you have set the APP_KEY and JWT_SECRET correctly in your environment. You can see instructions for that here: https://github.com/HiEventsDev/hi.events-digitalocean** => I don't use Digital ocean.

I used this link: https://github.com/HiEventsDev/hi.events?tab=readme-ov-file#-quick-start-with-docker.
I thought everything was already configured in docker-compose.

**If you change your APP_DEBUG environment variable to true and then attempt to create an account with a different email you should see the error.** => I try now :)

I think my email server may be set incorrectly. I'm at Zoho. I never received an email having configured this as the documentation requests.

MAIL_MAILER=smtp
MAIL_HOST= smtp.zoho.eu
MAIL_PORT=587	
MAIL_USERNAME=mymail@mydocmain.com	
MAIL_PASSWORD=mystrongpassword

**Comment by zarevskaya** [comment]
Hi @daveearley 
I don't understand why, but it's positive, I no longer have errors.

Reinstallation from scratch. Mail server works perfectly too. Great!

In fact my idea is to write an article for a [French-speaking blog](https://belginux.com/), do you think it would be easy to contribute to the French translation of your application?

Thanks for the support :)

**Comment by daveearley** [comment]
Great! And yes, contributions are more that welcome for translations. Translations are high on my list of priorities. And French will be in the first [set of languages included](https://github.com/HiEventsDev/hi.events/tree/main/frontend/src/locales) 🇫🇷 

Also, I'd be very grateful for a mention in an article. Thanks!

**Comment by eademir** [comment]
When I first run the docker compose I faced the same issue but after a rerun, it's fixed.
