### ISSUE TITLE
🐛  Correction in the translation file

### ISSUE THREAD

**Issue by zarevskaya** [HiEventsDev/hi.events#43]
Hi,

Maybe I'm wrong, but I think the following points are worth checking. I think that if I modify these lines myself, it will cause an error. I think...

Maybe this is normal and I need to translate differently. Can you confirm?

2199
#: src/components/modals/SendMessageModal/index.tsx:211
msgid ""
"Only important emails, which are directly related to this event, should be sent using this form.\n"
"Any misuse, including sending promotional emails, will lead to an immediate account ban."
msgstr ""

////
2448

#: src/components/modals/SendMessageModal/index.tsx:207
#~ msgid ""
#~ "Please ensure you only send emails directly related to the order. Promotional emails\n"
#~ "should not be sent using this form."
#~ msgstr ""

/////
3444

#: src/components/common/TicketsTable/SortableTicket/index.tsx:56
msgid ""
"This ticket cannot be deleted because it is\n"
"associated with an order. You can hide it instead."
msgstr ""

/////
3554

#: src/components/forms/TicketForm/index.tsx:203
msgid ""
"Tiered tickets allow you to offer multiple price options for the same ticket.\n"
"This is perfect for early bird tickets, or offering different price\n"
"options for different groups of people."
msgstr ""

///

Have a nice day!

**Comment by daveearley** [comment]
To update translations you should edit the code rather than the translation files. Once you've updated the code you can run 

```bash
cd ./frontend && yarn messages:extract && yarn messages:compile
```

This will update the translation files for you.

**Comment by daveearley** [comment]
Assuming you follow the same pattern in the english file I think it should be fine. Were you encountering any specific error?

**Comment by zarevskaya** [comment]
No, everything is fine, sorry. On the other hand, for my part I have finished the translation, almost, I see that a lot is missing from your repository
