### ISSUE TITLE
🌟Add single-day events with multiple performance days.

### ISSUE THREAD

**Issue by mnfctrdinitaly** [HiEventsDev/Hi.Events#49]
**Is your feature request related to a problem? Please describe.**
In the current setup when I want to add an event, a theatre performance or dance show, and it happens on three different days I can't add all start times simultaneously? Normally on ticketing sites, theres the Main Show Page -> Each Event Day/Day.

**Describe the solution you'd like**
Would it be possible in the event creation page to allow a series of dates/times instead of just a blanket start time and end time? When patrons visit the site it would be helpful for them to see ALL times and dates available for purchase instead of separate sites for each date/time.

**Describe alternatives you've considered**
This is pretty basic and necessary for a ticketing software to provide. Otherwise you limit your market to conferences/convension/festivals?

**Additional context**
Here's an example of what I am talking about.
![Screen Shot 2024-06-16 at 12 15 13 PM](https://github.com/HiEventsDev/hi.events/assets/95198669/33ed9485-ac26-4c51-a55f-e9713f2c41e2)

**Comment by daveearley** [comment]
Hi @mnfctrdinitaly,

Thanks for the request. You can use tickets and put the date and time in the ticket name. This is similar to how [EventBrite handles it](https://www.eventbrite.ca/help/en-ca/articles/454084/how-to-setup-a-multi-date-multi-location-event/). 

I do agree in cases like this it would be useful to hide the start and end date. I'll add this as an event setting. 

<img width="845" alt="Screenshot 2024-06-16 at 12 39 21" src="https://github.com/HiEventsDev/hi.events/assets/166798/cfff40d4-b82b-4ae7-b00d-5be4fb0655b9">


<img width="1512" alt="Screenshot 2024-06-16 at 12 40 39" src="https://github.com/HiEventsDev/hi.events/assets/166798/c5d23426-745d-4f76-9ed5-d83f7b13bcec">

**Comment by mnfctrdinitaly** [comment]
Thanks for the quick response. This is a usable work around, would this work in conjunction with a tiered ticket? 
**For example**

| Date | Tier | Price |
|----|----|----|
|Friday 7:00 PM| Student Ticket| $10.00|
|Friday 7:00 PM| Adult Ticket| $10.00|
|Friday 7:00 PM| VIP Ticket| $10.00|
|Saturday 2:00 PM| Student Ticket| $10.00|
|Saturday 2:00 PM| Adult Ticket| $10.00|
|Saturday 2:00 PM| VIP Ticket| $10.00|
|Saturday 7:00 PM| Student Ticket| $10.00|
|Saturday 7:00 PM| Adult Ticket| $10.00|
|Saturday 7:00 PM| VIP Ticket| $10.00|
|Sunday 2:00 PM| Student Ticket| $10.00|
|Sunday 2:00 PM| Adult Ticket| $10.00|
|Sunday 2:00 PM| VIP Ticket| $10.00|

This feels like it might become cumbersome. Would you still suggest each date/time being it's own ticket?

**Comment by daveearley** [comment]
Sorry, missed your last comment. Yes it would work in conjunction with tiered tickets also. It is slightly cumbersome, but we'll be adding additional functionality to make managing multi-day events very soon.

**Comment by grablair** [comment]
Is this actually completed? Or is it being tracked in a different issue?
