### ISSUE TITLE
Unable to initialize the project using Docker all in one. 🐛

### ISSUE THREAD

**Issue by Romerolweb** [HiEventsDev/hi.events#5]
**Describe the bug**
When I am trying to initialize the project following the guide, I got this error.

**To Reproduce**
Navigate to the Docker Directory:

    cd hi.events/docker/all-in-one

Run the set-up script:

    docker-compose up -d

**Expected behavior**

**Screenshots**

**Desktop :**
 - OS: windows
 - Visual studio terminal
 - 
**Hi.Events Version and platform**
I am using the lastest version of Hi.Events.

**Logs**
Navigate to the Docker Directory:

cd hi.events/docker/all-in-one
Run the set-up script:

docker-compose up -d

**Additional context**
I would like to try it.

**Comment by daveearley** [comment]
Hi @Romerolweb, thanks for creating an issue! 

Was there any error output when you ran `docker-compose up -d`?

**Comment by gitmotion** [comment]
im getting a similar issue when running `docker compose up -d` 
exiting on startup
![image](https://github.com/HiEventsDev/hi.events/assets/43588713/f34679a0-f503-4463-b5b1-48a468cc84c2)

**Comment by NelsonDane** [comment]
I've had this happen before with Docker images built on Windows. I belive this [StackOverflow](https://stackoverflow.com/a/56791772) should fix it. Need to change `startup.sh`  from CRLF to LF. If this is indeed the fix, I can make a small PR so that it does this automatically when building the Docker image @Romerolweb @gitmotion

**Comment by Romerolweb** [comment]
I will take a look and will let you know


[image: facebook] <https://www.facebook.com/sebastianromero100ipuc>
[image: twitter] <https://twitter.com/romerolopina>

Sebastian  Romero Laguna

Software design and Web applications

"Todo lo puedo en Cristo que me fortalece"
Filipenses 4:13


+57  <+57+3164154111>3025907794
***@***.***

Proyectos <https://github.com/Romerolweb>

**Comment by gitmotion** [comment]
@NelsonDane awesome thanks for that, can confirm changing CRLF to LF on the startup.sh file has resolved the build issue! 

now im getting a different issue of possibly the app not being able to connect with the pg database with a 500 error when trying to register a user
![image](https://github.com/HiEventsDev/hi.events/assets/43588713/f93bf31b-2247-41a9-8371-4c7748af452e)

im just cloning the repo, changing the lineendings of startup.sh file to LF and then composing. i was testing this on docker on windows before deploying it on a linux system so maybe that will just resolve all these issues but it would be great to just have a docker image to pull from. but i may just have to try it on my linux environment
