### ISSUE TITLE
🌟 Add an option to duplicate an event

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/hi.events#51]
It would be great on the '/manage/organizer/[id]' page if you could duplicate an event that reoccurs often, for example a ticketed event that happens every week or reoccurs at random times in the future. 

The drop down menu that shows the three options, View event page, Manage event and Check-in could have an option duplicate event.  The date and time could be then editted without having to recreate the whole event contents.

**Comment by daveearley** [comment]
Good suggestion! Cloning and archiving will be coming very soon.

**Comment by daveearley** [comment]
The latest release has the ability to clone event 👍
