### ISSUE TITLE
🌟Improve date and time display on event page

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/hi.events#54]
On the event page it shows the date and time in the following format.

Date & Time
Jul 26, 2024 1:00pm
Jul 26, 2024 3:00pm

It would be nice to have these labelled with the Start and End so people know what the two times mean.  It would also be nice to have the day shown.  For example:

Date & Time
Friday, July 26, 2024 1:00pm to Friday, July 26, 2024 3:00pm

**Comment by daveearley** [comment]
That's a good point. I'll update it to be more clear.
