### ISSUE TITLE
🌟Ability to add links in questions / question options

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/Hi.Events#58]
It would be nice to be able to add links to either the question or question options.  For example, I would like to add a checkbox question such as the following.

Terms and Conditions
I agree to the ticketing terms and conditions

I would then like the "terms and conditions" text to link to open the terms and conditions in a new window.  This doesn't seem possible in the current setup.  Maybe this could be done by adding markdown link support, or autoconverting URLs to links.  Autoconverting the links could then have a question like following.

Terms and Conditions
I agree to the ticketing terms and conditions at https://www.example.com/terms

Where https://www.example.com/terms would automatically link and open in a new window without requiring any code or markdown support.

**Comment by daveearley** [comment]
Good suggestion! Rather than using a checkbox, this could be achieved by adding a new "terms" question type with the ability to either add a terms link or a block of HTML.
