### ISSUE TITLE
🐛 Widget JS doesn't details domain correctly

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/hi.events#59]
When using the widget script it seems to fail consistently on the following code:

`const scriptURL = document.currentScript.src;`

The `document.currentScript` will return null sometimes and then the widget won't load.  I believe this is related to the callback but it doesn't always have a null value.

**Comment by daveearley** [comment]
Thanks for reporting @elronalds. Can you check if this is fixed on the latest release?
