### ISSUE TITLE
🐛 Can't change default currency in account settings

### ISSUE THREAD

**Issue by anarion80** [HiEventsDev/hi.events#61]
**Describe the bug**
Can't change default currency in Account Settings. After changing from default USD to something else and clicking `Save Settings`, there is a notification `Please check the provided information is correct` and an error in the console.

**To Reproduce**
1. Go to Account Settings
2. Change Currency
3. Click `Save Settings`

**Expected behavior**
Currency is changed without any errors

**Screenshots**
![image](https://github.com/HiEventsDev/hi.events/assets/2185791/c09b2b23-ea32-41ab-b206-d6fd781dfe18)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 126.0.2592.61

**Hi.Events Version and platform**
This is in Docker, with separate backend, frontend, database, redis and nginx.

**Logs**
POST request payload:

```json
{"name":"Anarion Dunedain","currency_code":"PLN","timezone":"Europe/Warsaw","id":1,"updated_at":"2024-06-19T14:45:22.000000Z","stripe_connect_setup_complete":false,"is_account_email_confirmed":false}
```

**Comment by daveearley** [comment]
Thanks for reporting @anarion80! This should be fixed now.
