### ISSUE TITLE
🐛 Messages list giving 500 error after sending an email to attendees

### ISSUE THREAD

**Issue by gitmotion** [HiEventsDev/hi.events#71]
**Describe the bug**
Messages list giving 500 error after sending an email to attendees and will not load

**To Reproduce**
1. send a message to all attendees of an event
2. i got an error message
3. but i looked at my email host and it looks like all the messages sent succesfully
4. however when i go back to the messages screen it does not load the list

**Expected behavior**
It should show and not error out when sending messages to all attendees

**Screenshots**
![image](https://github.com/HiEventsDev/hi.events/assets/43588713/7f4e7560-6aa2-46d7-a9ab-37f572275136)
![image](https://github.com/HiEventsDev/hi.events/assets/43588713/2d1ed02b-aeff-4a01-937b-53019eb681aa)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: Chromium 
 - Version: 1.67.119

**Smartphone (please complete the following information):**
n/a

**Hi.Events Version and platform**
Docker 

**Logs**
Add any relevant error logs 

**Additional context**

**Comment by daveearley** [comment]
Thanks for the report. Is there any stack trace in the logs?

**Comment by gitmotion** [comment]
@daveearley afk at the moment but i've tested sending the message with and without emojis and noticed that it sends fine without some of the emojis here is the list of emojis used in that message: 📃🏢🏠🛬🅿️🚦📱🍸😉💊🥽🚿
not sure if one of the emojis is affecting the way the message is stored in the db. after hard deleting the message with the emojis from the postgres database manually the message list works fine again

**Comment by gitmotion** [comment]
that's awesome, just pulled the latest image and it works perfectly. thank you!
