### ISSUE TITLE
🐛 Waiting list form doesn't go through and opens new tab with json response

### ISSUE THREAD

**Issue by Psypher1** [HiEventsDev/Hi.Events#81]
**Describe the bug**

**To Reproduce**
1. Go to https://dashboard.mailerlite.com/forms/953448/121811238849086471/share
2. Enter email address
3. Click subscribe

**Expected behavior**
A confirmation that my email has been added to waiting list

**Screenshots**
![evnets1](https://github.com/HiEventsDev/hi.events/assets/34038162/f6a661f3-94bc-4358-b385-3546a8e139b2)

![events2](https://github.com/HiEventsDev/hi.events/assets/34038162/8e5a20a6-28e5-41cb-bea3-eeda7da34694)

**Desktop (please complete the following information):**
 - Windows
 - Firefox

**Comment by daveearley** [comment]
Thanks for the report @Psypher1! That looks like an issue with Mailerlite, the platform we use for our newsletter. 

I'll reach out to them and let them know.

**Comment by Psypher1** [comment]
Absolutely, my pleasure.
