### ISSUE TITLE
Error 500 while signup an account

### ISSUE THREAD

**Issue by SergioSSantiago** [HiEventsDev/Hi.Events#88]
"message": "file_put_contents(/app/storage/logs/query.log): Failed to open stream: Permission denied",
    "exception": "ErrorException",
    "file": "/app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php",
    "line": 275,

**Comment by daveearley** [comment]
Hi @SergioSSantiago, 

Thanks for the report.

This error is related to the query logging which is used for debugging. To disable it you can set the `APP_DEBUG` environment variable to `false`. 

I've also [disabled the functionality](https://github.com/HiEventsDev/Hi.Events/pull/89) by default, so it you use the latest release that will also fix it.

Thanks

**Comment by SergioSSantiago** [comment]
[TransportException](https://hi-events-5g23c.ondigitalocean.app/api/auth/forgot-password#trace-box-1)
HTTP 500 Internal Server Error
Failed to authenticate on SMTP server with username "d8f68db9-c499-4112-b009-4ef769477440" using the following authenticators: "LOGIN", "PLAIN". Authenticator "LOGIN" returned "Expected response code "235" but got code "501", with message "501 Username used for auth is not valid email address".". Authenticator "PLAIN" returned "Expected response code "235" but got empty code.".

**Comment by daveearley** [comment]
It looks like the username for the SMTP server must be a valid email address. The error message "501 Username used for auth is not valid email address" indicates this. Please check the SMTP configuration and ensure that the username is correctly set to a valid email address format (e.g., user@example.com). Also, verify the SMTP server address, port, and security settings. 

Let me know if that solves it.
